### ISSUE TITLE
macの自動ビルド産物を実行しようとするとエラーが出るのを解決したい

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox_engine#163]
## 内容

今macのGithub Actionsの産物を実行しようとすると、.soが使えない旨のエラーが表示されます。
https://github.com/Hiroshiba/voicevox_engine/pull/156#discussion_r738525132

これを表示されないようにしたいです。

### Pros 良くなる点

ユーザーにとってわかりやすい

### 実現方法

<s>scipyのopenblasを利用していること主原因だと思います。

numpyはopenblasを別途インストールしなくても良いらしいので、nuitikaビルドのパラメータを変えればビルドできるかも・・・？
https://numpy.org/install/#numpy-packages--accelerated-linear-algebra-libraries

もしくは別途brewなどでopenblasをインストールしてくるのも最終手段としていいかなと思います。
（openblasは50MBほどとちょっとだけ重いので、可能なら２個入るのは避けた方が良さそうです）</s>

↑違いそうでした。

**Comment by HyodaKazuaki** [comment]
> なるほどです。 認識を確認したいのですが、プルリクエストのコメントで紹介されている `codesign -f -s 'Common name' scipy/**/*.so` を実行しなくても警告が出ない、ということでしょうか？👀

おっしゃるとおりです。
ReleaseからMacOS向けにビルドされた7ZIPファイルをダウンロード/展開し、`run`に実行権限を与えただけで実行することができました。

**Comment by Hiroshiba** [comment]
なるほどです・・・！
僕がやったところ、.soや.dylibの確認が何度も入りそうでした。
`App Storeと確認済みの開発元からのアプリケーションを許可`をしていなくても、せめて聞かれる回数が１回で済むようにしたいかもです。

でもエラー見てる感じ、openblas周りではなさそうでした。
ということでissueの内容をちょっと修正したいと思います。

**Comment by PickledChair** [comment]
試してみたのでご報告します。結果は @Hiroshiba さんの場合と同じになりました。`run` の実行を許可したあと、実行すると以下のようなダイアログが出ます。

<img width="295" alt="couldnot_verify_so" src="https://user-images.githubusercontent.com/41382894/139562663-40b01a3b-1bea-42d4-8204-957bb60b4e52.png">

画像中の `libpython3.7m.dylib` を実行許可しても、他の .so や .dylib について同じダイアログが出続けます。アプリケーションの実行許可設定は「App Storeと確認済みの開発元からのアプリケーションを許可」にしてあります。

@HyodaKazuaki さんのご指摘で

> 7zに圧縮している影響かもしれません。

とありましたが、ダイアログのメッセージを見るに解凍アプリで解凍したことが OS 側で記録されているようなので、確かにその可能性もありそうです。

**Comment by PickledChair** [comment]
あと、これは実験してみただけなのですが、無理やり bundle 化すると実行できることを確認しました。

<details>
<summary>bundle のディレクトリ構造</summary>
<pre>
<code>
VoicevoxEngine.app
└── Contents
    ├── Info.plist
    ├── MacOS
    │   └── 解凍したフォルダ (macos-x64) の中身
    └── Resources（空のフォルダ）
</code>
</pre>
</details>

<details>
<summary>Info.plist の内容</summary>
<pre>
<code>
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;!DOCTYPE plist PUBLIC &quot;-//Apple Computer//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
&lt;plist version=&quot;1.0&quot;&gt;
  &lt;dict&gt;
    &lt;key&gt;CFBundleExecutable&lt;/key&gt;
    &lt;string&gt;run&lt;/string&gt;
    &lt;key&gt;CFBundlePackageType&lt;/key&gt;
    &lt;string&gt;APPL&lt;/string&gt;
    &lt;key&gt;CFBundleSignature&lt;/key&gt;
    &lt;string&gt;????&lt;/string&gt;
  &lt;/dict&gt;
&lt;/plist&gt;
</code>
</pre>
</details>

以上の bundle を起動すると、GUI上は VoicevoxEngine.app が起動を試みたあと静かに終了するように見えますが、アクティビティモニタで確認すると起動し続けていることがわかります。

この状態で

```
$ echo -n "こんにちは、音声合成の世界へようこそ" >text.txt
$ curl -s -X POST "localhost:50021/audio_query?speaker=1" --get --data-urlencode text@text.txt > query.json
$ curl -s -H "Content-Type: application/json" -X POST -d @query.json "localhost:50021/synthesis?speaker=1" > audio.wav
```

と実行すると、期待通りの音声ファイルが得られます。 http://localhost:50021/docs にアクセスしてドキュメントを見ることもできました。 VoicevoxEngine.app を終了するにはアクティビティモニタから強制終了します。

実用的な方法ではないと思いますが、実行を許可さえできれば期待通りに動くことは確認できました。

**Comment by Hiroshiba** [comment]
報告感謝です！
あとは何度も聞かれるのを失くすだけ、という感じなんですね。

**Comment by PickledChair** [comment]
> あとは何度も聞かれるのを失くすだけ、という感じなんですね。

手元で手動で bundle にしたものは何も聞かれずに済みましたが、おそらく外部からダウンロードした bundle についても初回起動時に１回聞かれるだけで済むと思います（開発元が未確認の .app を実行する方法はいくつかあります。参考： https://support.apple.com/ja-jp/guide/mac-help/mh40616/mac 。この実行の際、内部の実行ファイルや共有ライブラリについてはいちいち聞かれないはずです。.app に対しての１回で済みます）。

とはいえ、bundle 化しない状態で、何度も聞かれないようにする方が自然ですよね😅（特にエンジンにおいては。）

少し思いついたのは、VOICEVOX エディタ（エンジンではなく）において、 .app 内にエンジンのファイル群が配置されていれば、やはり同じように初回起動時に１回聞かれるだけで済むのではないか、という予想です。もしそうであれば、 この Issue の問題が解決しない場合でも、VOICEVOX エディタの実行を介したエンジンの起動は可能と考えられます。

**Comment by Hiroshiba** [comment]
あ、なるほどです！！
runという実行バイナリになっているから何度も聞かれるのであって、appバンドルにしてしまえば１回だけかもしれないんですね！！

すみません、そこは考えが及びませんでした、であれば今runバイナリで何度も聞かれるのはまあ別に良いのかなと思いました！

.appにしても何度も聞かれるようであればまた再考したいと思います。
（説明ありがとうございました・・・！）

**Comment by PickledChair** [comment]
https://github.com/Hiroshiba/voicevox_engine/issues/163#issuecomment-955620365 で各 dylib に対して警告ダイアログが出て run の実行が大変なことを報告しましたが、各 dylib に許可を与えなくても動作する方法を発見したので、一応報告します。

今回は https://github.com/Hiroshiba/voicevox_engine/releases/tag/0.8.0 からダウンロードした macos-x64.7z.001 ファイルを解凍して使用しました。また、前回の報告時は解凍に Mac App Store で公開されている [The Unarchiver](https://apps.apple.com/jp/app/the-unarchiver/id425424353?mt=12) という GUI アプリケーションを使いました。今回代わりに、Homebrew で入手できる [p7zip](https://formulae.brew.sh/formula/p7zip) という CUI ツールを使ったところ、 `chmod +x run` だけでエンジンを起動できました。以下手順です：

```
$ ls
macos-x64.7z.001
$ brew install p7zip

...

$ 7z x macos-x64.7z.001

...

$ ls
macos-x64
macos-x64.7z.001
$ cd macos-x64
$ chmod +x run
$ ./run
```

警告ダイアログが出ることなく実行可能になった理由は分かりませんが、ターミナルを介して解凍したことで OS 側がバイナリを信頼したか、あるいは解凍アプリケーションの仕様に依存しているかのどちらかだと考えています（ @HyodaKazuaki さんが https://github.com/Hiroshiba/voicevox_engine/issues/163#issuecomment-955128721 で実行可能であることを報告された時も、ターミナルで何らかの CUI ツールを使ったと思われるのですが、どうされていたのでしょうか？）。

**Comment by PickledChair** [comment]
追加の報告： 同じ CUI ツールであっても、 [unar](https://formulae.brew.sh/formula/unar) を Homebrew でインストールし、 `unar macos-x64.7z.001` コマンドで解凍したファイルを用いると、警告ダイアログの問題は解消されませんでした。解凍アプリケーションの仕様に依存するということが濃厚です。

**Comment by Hiroshiba** [comment]
なるほどです。ツールによって変わる可能性は気づきませんでした…。
