### ISSUE TITLE
nuitkaビルドしたエンジンにおいて、resampyがエラーを吐く

### ISSUE THREAD

**Issue by y-chan** [Hiroshiba/voicevox_engine#167]
## 不具合の内容

題の通り

### 現象・ログ

![image](https://user-images.githubusercontent.com/34832037/139592054-8fab67f1-9141-4102-baa3-e82d97e67764.png)

### 再現手順

- https://github.com/Hiroshiba/voicevox/pull/426 で製品版エンジンを用いてサンプリングレートを変更して音声書き出しを実行してみる

### 期待動作

製品版でもサンプリングレートを変更して音声書き出しができる

## VOICEVOXのバージョン

0.7.5
(多分サンプリングレート変更を適用した時からダメ)

## OSの種類/ディストリ/バージョン

Windows 11 Pro 64bit

## その他

Windows 11なので、ワンチャンおま環です。どなたかほかにWindows 10とかで試して再現するか教えていただけると幸いです。

**Comment by Hiroshiba** [comment]
ちょっと謎なエラーですね。float64になってたりするんでしょうか・・・？

**Comment by takana-v** [comment]
今更ですが、windows10でも同じエラーが出ました。（44100Hz）

https://github.com/Hiroshiba/voicevox_engine/blob/b974ddc200cbebc06bdd92cdf3fd5d9e2cf6248f/voicevox_engine/synthesis_engine.py#L470-L475

**Comment by Hiroshiba** [comment]
検証ありがとうございます。直したいところですね･･･。

scipyのresampleに移行してもいいも、とちょっと話していました。
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.resample.html

実際に２つの方法で音声をリサンプリングしてみて、違いを感じるか聴き比べるのが良いのかなと思っています。

**Comment by takana-v** [comment]
coreのmockでリサンプリングを外したものは音割れがひどかったですが、resampyのリサンプリング処理でちゃんとした音声になっていました。
しかし、scipyのリサンプリングではそのままの品質でした。
(mockでの例はダウンサンプリングなので、アップサンプリングだと違った結果になるかもしれません)

**Comment by takana-v** [comment]
上のブランチでリリースしたものを試してみました。
https://github.com/takana-v/voicevox_engine/releases/tag/build-test6
自分の耳では違いが分かりませんでした。
再生できないからサンプリングレートを変える、という目的にはよさそうですが、音質を上げる目的には合ってなさそうです。

**Comment by y-chan** [comment]
> 再生できないからサンプリングレートを変える、という目的

もともとリサンプリング機能はその目的で私が追加(#31)したものです。なので、音質向上になっている必要はないと思います。
私も手元でscipyによるリサンプリングを試してみましたが、特に大きな問題は見当たりませんでした。
よって、scipyで置き換えるので十分何とかなりそうです。

**Comment by Hiroshiba** [comment]
アップサンプリングは基本的に、聞いた時の品質が劣化してなければ大丈夫です！
