### ISSUE TITLE
 CharactorInfoが必要な情報（立ち絵など）をエンジンに実装する

### ISSUE THREAD

**Issue by takana-v** [Hiroshiba/voicevox_engine#169]
## 内容
題の通り
- https://github.com/Hiroshiba/voicevox/issues/429

### 実現方法
必要な情報は以下の感じでしょうか。
- policy.md
- portrait.png
- icons/*.png
- voice_samples/*.wav（要らないかも？）

speaker_uuidを投げたら以上の情報が返ってくるのを想定しています。
バイナリはbase64エンコードしてjsonを返す、もしくは`multipart/form-data`を使う、という方法があると思います。
フロント側で実装しやすい方で実装すればいいかなと思います。

## その他
現在はコアに情報が集まっているので、エンジンはコアから渡されたデータを素通りさせる形式の方が良いかもしれません。

~~後、http通信なのでwiresharkとか使うと画像データを見られるかもしれません。~~
そもそもAPIにアクセスすれば誰でも見れますね...失礼しました。
画像周りのライセンスを確認する必要がありそうです。

**Comment by Hiroshiba** [comment]
良いと思います！！

> voice_samples/*.wav（要らないかも？）

一応これも返す仕様を考えたいです。

> バイナリはbase64エンコードしてjsonを返す、もしくはmultipart/form-dataを使う、という方法があると思います。

`multipart/form-data`ってレスポンスで使えましたっけ👀（単純に知らないだけです）
もし使えるならこちらが良さそうな気がします！
無理そうならbase64したものを含む巨大なjsonを返すのが良いのかなと感じました！

**Comment by takana-v** [comment]
> multipart/form-dataってレスポンスで使えましたっけ👀（単純に知らないだけです）

fastapiのResponseクラスはヘッダーもボディーも手動で設定できるので、一応可能です。
ただ、フロント側でそれを解釈できるかどうかは分からないです。（通常はpostで使うものなので...）
jsonが無難かな、と思います。

**Comment by Hiroshiba** [comment]
あ、たしかに！　`multipart/form-data`で返すことはいくらでもできそうです。
がまあたぶんクライアントでいい感じに処理できる機構が無い気がするので、仰るとおりjsonが無難な気がしました。

**Comment by shirowanisan** [comment]
すみません。横から失礼します。

> speaker_uuidを投げたら以上の情報が返ってくるのを想定しています。

キャラクター情報をエンジンがもつため、フロントエンドはどんな`speaker_uuid`があるか知らないことになります。

フロントエンドの実装にもよりますが、`speaker_uuid`リストを返すようなエンドポイントが必要かもしれません。
このとき`speaker_uuid`リストはjsonを読み込む形式がサードパーティ開発者が操作しやすいと思いました。
```
{
    "speakerUuids": [
        "dummy1uuid",
        "dummy2uuid"
    ]
}
```

**Comment by Hiroshiba** [comment]
まさしくそういう用途のために`/speakers`エンドポイントがあります！！
https://github.com/Hiroshiba/voicevox_engine/blob/78c31e177ab9167840919a39163b21d47389e5d7/run.py#L606-L611

**Comment by shirowanisan** [comment]
すみません。既にエンドポイントはあったんですね。了解しました。
