### ISSUE TITLE
macOSビルドの実行時に Symbol not found のエラーが起きる

### ISSUE THREAD

**Issue by PickledChair** [Hiroshiba/voicevox_engine#193]
## 不具合の内容

[autobuild-check-20211119](https://github.com/Hiroshiba/voicevox_engine/releases/tag/autobuild-check-20211119) のmacOS向けビルドを実行すると、一部の .dylib ファイル（libtorch_cpu.dylib と libc10.dylib）において必要なシンボルが見つからず、実行時エラーとなる。

### 現象・ログ

「再現手順」通りにエンジンを実行すると、以下のエラーが出力されます：

```
$ ./macos-x64/run
Traceback (most recent call last):
  File "/path/to/macos-x64/voicevox_engine/synthesis_engine.py", line 512, in make_synthesis_engine
ImportError: dlopen(/path/to/macos-x64/core.so, 0x0002): Symbol not found: __ZN5torch3jit6MethodclENSt3__16vectorIN3c106IValueENS2_9allocatorIS5_EEEERKNS2_13unordered_mapINS2_12basic_stringIcNS2_11char_traitsIcEENS6_IcEEEES5_NS2_4hashISE_EENS2_8equal_toISE_EENS6_INS2_4pairIKSE_S5_EEEEEE
  Referenced from: /path/to/macos-x64/libcore.dylib
  Expected in: /usr/local/Cellar/libtorch/1.10.0/lib/libtorch_cpu.dylib
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
Traceback (most recent call last):
  File "/path/to/macos-x64/run.py", line 667, in <module>
  File "/path/to/macos-x64/voicevox_engine/synthesis_engine.py", line 542, in make_synthesis_engine
  File "/path/to/macos-x64/voicevox_engine/dev/core/mock.py", line 76, in metas
  File "/path/to/macos-x64/pathlib.py", line 1221, in read_text
  File "/path/to/macos-x64/pathlib.py", line 1208, in open
  File "/path/to/macos-x64/pathlib.py", line 1063, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/macos-x64/voicevox_engine/dev/core/../../../VERSION.txt'
```

### 再現手順

1. https://github.com/Hiroshiba/voicevox_engine/releases/tag/autobuild-check-20211119 のmacOS向け配布物をダウンロード
2. `7z x macos-x64.7z.100` で解凍（7z コマンドは `brew install p7zip` で入手可能）
3. `chmod +x macos-x64/run`
4. `./macos-x64/run`

### 期待動作

再現手順通り実行するとエンジンが正常動作する。

## VOICEVOXのバージョン

0.8.0
([autobuild-check-20211119](https://github.com/Hiroshiba/voicevox_engine/releases/tag/autobuild-check-20211119))

## OSの種類/ディストリ/バージョン

macOS Monterey (version 12.0.1), Intel Mac

## その他

「現象・ログ」のメッセージにおいて、 `Notice: mock-library will be used. Try re-run with valid --voicevox_dir` 以降は仕様だと思うので無視します。重要なのは

```
Symbol not found: __ZN5torch3jit6MethodclENSt3__16vectorIN3c106IValueENS2_9allocatorIS5_EEEERKNS2_13unordered_mapINS2_12basic_stringIcNS2_11char_traitsIcEENS6_IcEEEES5_NS2_4hashISE_EENS2_8equal_toISE_EENS6_INS2_4pairIKSE_S5_EEEEEE
  Referenced from: /path/to/macos-x64/libcore.dylib
  Expected in: /usr/local/Cellar/libtorch/1.10.0/lib/libtorch_cpu.dylib
```

というエラーメッセージです。名前マングリングが激しくて一見よくわかりませんが、libtorch_cpu.dylib に期待するメソッドが存在しなかったということを報告しています。フォークした自分のリポジトリの私家版ビルド（ https://github.com/PickledChair/voicevox_engine/actions/runs/1474788211 で得られる）は正常実行できるので、両者の差異を確かめるために、それぞれの libtorch_cpu.dylib に問題のSymbolが存在するかどうかを確かめてみました。

**[公式ビルド（autobuild-check-20211119）](https://github.com/Hiroshiba/voicevox_engine/releases/tag/autobuild-check-20211119)の libtorch_cpu.dylib：**

```
$ nm -gU libtorch_cpu.dylib | grep __ZN5torch3jit6MethodclENSt3__16vectorIN3c106IValueENS2_9allocatorIS5_EEEERKNS2_13unordered_mapINS2_12basic_stringIcNS2_11char_traitsIcEENS6_IcEEEES5_NS2_4hashISE_EENS2_8equal_toISE_EENS6_INS2_4pairIKSE_S5_EEEEEE
$ # 出力なし
```

**[私家版ビルド](https://github.com/PickledChair/voicevox_engine/actions/runs/1474788211 )の libtorch_cpu.dylib：**

```
$ nm -gU libtorch_cpu.dylib | grep __ZN5torch3jit6MethodclENSt3__16vectorIN3c106IValueENS2_9allocatorIS5_EEEERKNS2_13unordered_mapINS2_12basic_stringIcNS2_11char_traitsIcEENS6_IcEEEES5_NS2_4hashISE_EENS2_8equal_toISE_EENS6_INS2_4pairIKSE_S5_EEEEEE
0000000001dce260 T __ZN5torch3jit6MethodclENSt3__16vectorIN3c106IValueENS2_9allocatorIS5_EEEERKNS2_13unordered_mapINS2_12basic_stringIcNS2_11char_traitsIcEENS6_IcEEEES5_NS2_4hashISE_EENS2_8equal_toISE_EENS6_INS2_4pairIKSE_S5_EEEEEE
$ # 問題のシンボルが期待通りに存在する
```

これを受けて、公式ビルドの libtorch_cpu.dylib を私家版ビルドのものに入れ替えてみました。するとエラーメッセージが変わります：

```
$ ./macos-x64/run
Traceback (most recent call last):
  File "/path/to/macos-x64/voicevox_engine/synthesis_engine.py", line 512, in make_synthesis_engine
ImportError: dlopen(/path/to/macos-x64/core.so, 0x0002): Symbol not found: __ZN3c1010TensorImpl12_set_fw_gradERKN2at6TensorES4_yb
  Referenced from: /path/to/macos-x64/libtorch_cpu.dylib
  Expected in: /usr/local/Cellar/libtorch/1.10.0/lib/libc10.dylib
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
Traceback (most recent call last):
  File "/path/to/macos-x64/run.py", line 667, in <module>
  File "/path/to/macos-x64/voicevox_engine/synthesis_engine.py", line 542, in make_synthesis_engine
  File "/path/to/macos-x64/voicevox_engine/dev/core/mock.py", line 76, in metas
  File "/path/to/macos-x64/pathlib.py", line 1221, in read_text
  File "/path/to/macos-x64/pathlib.py", line 1208, in open
  File "/path/to/macos-x64/pathlib.py", line 1063, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/macos-x64/voicevox_engine/dev/core/../../../VERSION.txt'
```

libc10.dylib にも同様の問題があることがわかりました。これも同様に私家版ビルドのものに入れ替えると、エンジンが正常実行できるようになりました。以上より、実行に影響した .dylib ファイルは libtorch_cpu.dylib と libc10.dylib の２つのみと考えています。公式ビルドでは正しいバージョンの .dylib ファイルを含めることができていない可能性があります（今回は影響がなかっただけで、他の .dylib ファイルについても同じことが起こっている可能性があります）。

自動ビルドの手順自体は両者で全く同じのはずですが、このように自動ビルドを行なったリポジトリによって結果が異なってしまっています。~~個人的にはビルド結果のキャッシュが影響しているのではと考えています（自分のリポジトリでうまくいっているのは、環境構築がごく最近であったためと予想しています）が、今のところ原因を特定できていません。~~（←違ったようです。参考： https://github.com/Hiroshiba/voicevox_engine/issues/193#issuecomment-974115413 ）GitHub Actions による自動ビルドについて詳しい方のサポートが必要と思われます。

**Comment by Hiroshiba** [comment]
issueありがとうございます！！

> GitHub Actions による自動ビルドについて詳しい方のサポートが必要と思われます。

mac版ではbrew installによってlibtorchをインストールしていそうです。
https://github.com/Hiroshiba/voicevox_engine/blob/3fd85c0e360523e737a7fb1371bfa7af26ec6ce6/.github/workflows/build.yml#L33-L35

このあたりが関係あるかも・・・？
coreのビルドはたしか1.9.0でビルドしていますが、brew installだとより新しい1.10.0とかがインストールされるかもです。

他のOSだとバージョン指定でダウンロードしています。
https://github.com/Hiroshiba/voicevox_engine/blob/3fd85c0e360523e737a7fb1371bfa7af26ec6ce6/.github/workflows/build.yml#L269

brew installでバージョン指定するか、このURLでダウンロードするようにすると解決するかも・・・？
https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.9.0.zip

**Comment by PickledChair** [comment]
> coreのビルドはたしか1.9.0でビルドしていますが、brew installだとより新しい1.10.0とかがインストールされるかもです。
> 他のOSだとバージョン指定でダウンロードしています。

確認したら、 https://github.com/PickledChair/voicevox_engine/actions/runs/1474788211 の場合は libtorch の 1.9 系がインストールされていました。だから上手くいっているんですね（むしろなぜ自分のリポジトリで旧版がインストールされているのかわからないですね😅）。一方、公式リポジトリでは 1.10 系がインストールされていましたね。

Homebrew でバージョン固定するのは難しい（現時点で libtorch の 1.9 系をインストールする手段がない）ので、教えていただいた https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.9.0.zip のリンクからダウンロードするのが現実的ですね。これを利用した方法を考えてみます。

**Comment by Hiroshiba** [comment]
> これを利用した方法を考えてみます。

良いと思います！！
