### ISSUE TITLE
スピーカー一覧を返すAPIが欲しい

### ISSUE THREAD

**Issue by raa0121** [Hiroshiba/voicevox_engine#22]
アプリ連携をする際に、スピーカー名から `speaker_id` を引けるようにするためのAPIが欲しいです
```json
[
  {"name": "ずんだもん", "speaker_id": 1},
  {"name": "四国めたん", "speaker_id": 2}
]
```
な json を返してくれると嬉しいです。

**Comment by Hiroshiba** [comment]
すごくよくわかります。必要だと思います。
実装手順を整理してみます。

speaker_idと声の種類の対応を知っているのは、エンジン内で用いている「音声ライブラリ」（≒ディープラーニングしたモデル）です。
なので、音声ライブラリに情報取得APIを追加し、エンジン側で集約してソフトウェアに返すAPIを実装するのが良さそうです。

ただ今は音声ライブラリが一意なので、音声ライブラリのAPIを待たず、エンジン側にだけAPIをもたせても良いかもしれません。
その場合は、version APIのようにspeaker_infsoみたいなAPIを増やすと良いかもしれません。
https://github.com/Hiroshiba/voicevox_engine/blob/9f6d22b3bc39c7fd81056343115e684c019046b0/run.py#L169-L171
