### ISSUE TITLE
音声合成エンジンのモックを作る

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox_engine#27]
製品版がないと音声合成が動かないのは少し不便なので、とりあえずエンジンだけで音声合成ができるようなモックが有ると良さそうです。

モックがあれば、GitPodという初学者にとても向いていそうなサービスを利用できるかもしれません。
https://github.com/Hiroshiba/voicevox/issues/119

このエンジンで自然言語処理に用いているPyOpenJTalkには音声合成機能もあり、OS問わず動くように設計されているはずです。
こちらをモックとして活用できるかもしれません。
https://github.com/r9y9/pyopenjtalk/tree/60ea4df975003702a9b92a078ed76acd6d2802f1#tts

**Comment by Hiroshiba** [comment]
https://github.com/Hiroshiba/voicevox_engine/pull/53

**Comment by isnot** [comment]
> このエンジンで自然言語処理に用いているPyOpenJTalkには音声合成機能もあり、OS問わず動くように設計されているはずです。

上記指針に沿った形のモックを実装してみました。
しかしモックといいつつ、synthesis_engine.py に追加の実装をしており、イマイチ感はあります。
decode_forwardに入ってくる入力からは、テキスト状態のデータが失われており、しょうがないのでこのようにしました。
別のスマートな方法があれば、良いのですが…。

良いのか悪いのか不安なので、PRは保留しています。
https://github.com/isnot/voicevox_engine/commit/4280ebd9043b96991b78ad5d0ae2f538c5963d5c

**Comment by Hiroshiba** [comment]
@isnot pyopenjtalkの使用に関しては完璧だと感じました！　ドキュメントがあるのも素晴らしいです。
仰るとおりsynthesis_engine.pyに実装を追加しているのは避けたいなと感じました。
１つアイデアが有るのですが、`each_cpp_forwarder`のモックではなく、`SynthesisEngine`のモックにするというのはどうでしょう？

**Comment by isnot** [comment]
> 仰るとおりsynthesis_engine.pyに実装を追加しているのは避けたいなと感じました。

承知しました。
ひとまず、この続きは0.5.xの動向をみてからにしようと思います。

**Comment by Hiroshiba** [comment]
@isnot 0.5.0へのアップデートが完了しました！

実は今週末くらいに音声合成のコアライブラリを配布する予定でいます。
その際におそらく、linux版のVOICEVOXエンジンのビルドを試みる方も現れるかもしれません。
そのとき、このモックがあると、エラーの切り分けがやりやすくなりそうです。

どうでしょう、こちら進めてみませんか？ 👀

**Comment by isnot** [comment]
2つのPRを提出しました。

#77 は、前回の私の実装から、synthesis_engine.py へ加えるのをやめたバージョンです。🤔
#78 は、@Hiroshiba さんのアドバイスにあった、「SynthesisEngineのモック」です。😊

ご査収ください。🙇‍♀

**Comment by Hiroshiba** [comment]
モックが実装されました🎉
これでソフトウェア側で少し話題に上がっていたgitpodも使えるようになるかもしれません。
https://github.com/Hiroshiba/voicevox/issues/119

目的が達成されたのでcloseします。
