### ISSUE TITLE
pyopenjtalk が pip install できなくなっている

### ISSUE THREAD

**Issue by buckw6eat** [Hiroshiba/voicevox_engine#29]
ビルドに入る前に、URL 指定のコミットをチェックアウトできないようです。

<https://github.com/Hiroshiba/voicevox_engine/blob/d82d0859b5a585c9a848fbb7c6d9992e2e11b1f9/requirements.txt#L7>

> (venv) \> python -m pip install git+https://github.com/Hiroshiba/pyopenjtalk@69e5f354634f98098113f9cac5a6ea736443f9c9
Collecting git+https://github.com/Hiroshiba/pyopenjtalk@69e5f354634f98098113f9cac5a6ea736443f9c9
>  Cloning https://github.com/Hiroshiba/pyopenjtalk (to revision 69e5f354634f98098113f9cac5a6ea736443f9c9) to c:\users\buckw6eat\appdata\local\temp\pip-req-build-fip06c44
>  Running command git clone -q https://github.com/Hiroshiba/pyopenjtalk 'C:\Users\buckw6eat\AppData\Local\Temp\pip-req-build-fip06c44'
>  Running command git checkout -q 69e5f354634f98098113f9cac5a6ea736443f9c9
>  fatal: reference is not a tree: 69e5f354634f98098113f9cac5a6ea736443f9c9
> ERROR: Command errored out with exit status 128: git checkout -q 69e5f354634f98098113f9cac5a6ea736443f9c9 Check the logs for full command output.

<https://github.com/Hiroshiba/voicevox_engine/commit/89a8b4f7586fadba4f3ed0aa57ad82e2406b3884> で変更前の git ソース (from #7) からであればインストール可能です。

> git+https://github.com/r9y9/pyopenjtalk@59a33c04f81fab636e0f570708efea39bcd6b511

#16 なり #24 なりを崩すのに `requirements.txt` の再現性が欲しいのですが、戻してもよろしいでしょうか？

**Comment by Hiroshiba** [comment]
@buckw6eat 報告ありがとうございます。もととなっていたbranchを消去したためでした・・・。
branchを再pushしてみたので、実行できると思います。

**Comment by buckw6eat** [comment]
@Hiroshiba 確認いただきありがとうございます。実行可能になりました。
