### ISSUE TITLE
wavのサンプルレートについて

### ISSUE THREAD

**Issue by y-chan** [Hiroshiba/voicevox_engine#31]
初めまして。少し気になったことがあるので、Issueを起票させていただきます。

現状、wavの出力サンプルレートが24kHzに固定されていると思います。
こちら、24kHzで固定している理由は何かあるのでしょうか？
(音声合成の上で何かしら常識みたいなものであればすみません...)

このようなIssueを起票した理由としては、諸事情により48kHzで出力したいからです。
私自身は音声合成等に詳しくなく、その上VOICEVOX Engineが依存している他のライブラリ等にも詳しくないので、48kHzで出力しようとしてもうまくいかなかったのです。

出来れば48kHzに限らず、出力サンプルレートの変更を任意にできればよいかなと思い、起票させていただきました。

このIssueについてはエンドユーザー的に何も影響がなく、優先度の低いことだとは思いますが、よろしくお願いします。

**Comment by Hiroshiba** [comment]
24kHzになっているのは、VOICEVOXの内部技術の都合上そうなっているためです。
もちろん、品質を変えずに48kHzなどに変えることは可能です。

優先度の参考にしたいので、もしよければ48kHzで出力したい理由を伺いたいです。

**Comment by y-chan** [comment]
以前、本ライブラリを用いて https://github.com/y-chan/voicevox_discord_tts_sample というDiscord向けTTS Botを書きました。
現状は一度wavを吐き出し、FFmpegを用いて変換をしてからDiscordのボイスチャンネルに流しているのですが、この状態ではラグが大きいため、できればwavをそのまま流したいのです。
Discord BotライブラリにはDiscord.pyを使っていますが、これでwavを直接流すには48kHz/16bitである必要があるのです(要は品質の問題ではなく、ただただwavの仕様的に48kHz/16bitであればよいはずです)。
https://discordpy.readthedocs.io/ja/latest/api.html#pcmaudio

リサンプリングされていると思わしきコードを見つけ、値を調整することを試みたことがあるのですが、いまいちわからなかった、というのがこのIssueを起票した理由です。

**Comment by Hiroshiba** [comment]
なるほど、非常によくわかりました。

実装する場合、そのffmpegでリサンプリングされる処理を、VOICEVOX側に持たせることになると思います。
つまり最終的に音声が再生されるまでの時間は変わらなそうです。

**Comment by y-chan** [comment]
まだちゃんと検証したことはないですが、環境やファイルサイズによっては、ファイルの書き出しと読み込みの間でディスクIOの遅さが目立つ可能性があったので、VOICEVOX側で処理してしまうのが良いのかなぁと判断しました。

あと、下記のコードがresamplingしているものだと私は認識したので、ここの変更で何とかならないのかなと思ったのも一つです(勘違いであれば申し訳ないです)。
https://github.com/Hiroshiba/voicevox_engine/blob/66a1d0f89997f6c0262b3ff99ae47268df31bdf9/voicevox_engine/synthesis_engine.py#L289-L290
https://github.com/Hiroshiba/voicevox_engine/blob/66a1d0f89997f6c0262b3ff99ae47268df31bdf9/voicevox_engine/acoustic_feature_extractor.py#L10-L21

**Comment by Hiroshiba** [comment]
そのコードは音声合成する前の、データ前処理に当たり、変更しても24kHz以外で出力されません。

ファイルIOは考えていませんでした。リサンプリング機能があっても良いかなと思いました。
もしよければプルリクエストをいただけますか？

音声のリサンプリングは奥が深いため別途ライブラリが必要ですが、resampyがおすすめです。
[こんな感じ](https://resampy.readthedocs.io/en/master/api.html)で簡単にリサンプリングができます。

他にも、このリポジトリのコード解読の助けになりそうなヒントも紹介します。

<details>

[SynthesisEngineの最後](https://github.com/Hiroshiba/voicevox_engine/blob/66a1d0f89997f6c0262b3ff99ae47268df31bdf9/voicevox_engine/synthesis_engine.py#L303)でリサンプリングすることになると思います。

パラメータの足し方は https://github.com/Hiroshiba/voicevox_engine/pull/28 が参考になるかもしれません。

</details>
