### ISSUE TITLE
ずっと使っているとGPUメモリが消費されていくか調査

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox_engine#32]
長く使っているとGPUのメモリがあふれるというツイート・報告を見かけることがあります。
実際に調査してみる必要がありそうです。

CUDAをインストールすると`nvidia_smi`が付いてきて、これを用いるとメモリ使用量を把握できます。
![image](https://user-images.githubusercontent.com/4987327/130336026-913b4cbb-90d6-4df3-996f-fed6d986ecca.png)

**Comment by YouCuber** [comment]
1050tiの4GBで使ってますが、5文章くらいで溢れますね。
タスクマネージャのGPUメモリ使用量を見ていても短調増加で減ることがないです。
一回あふれるとRESTに500エラーが返りだし、VOICEVOX.EXEの再起動しか手がなくなります。

**Comment by Hiroshiba** [comment]
調査報告ありがとうございます！
なるほどです。応急処置として音声合成エンジンの再起動ができれば良さそうでしょうか。

**Comment by YouCuber** [comment]
基本そうですね。
クライアント側から再起動するためのRESTを用意するということでしょうか？
それともVOICEVOX側で自動検出して自動エンジン再起動ですか？

ちなみに、ツイッターのIDの文字列を一行づつ音声合成すると6行目くらいの必ず同じところで溢れる感じでしたのでメモリリークなのかもしれません。

**Comment by Hiroshiba** [comment]
エンジン側がエラーを吐いたらソフトウェア側からエンジンのプロセスを強制的に再起動する、というのを考えていましたが、
コメントを見て、エンジン側に再読み込みAPIを設けるのも良いなと思いました。

なるほど、おっしゃる通りメモリリークの可能性もありそうですね…
もしよろしければ、VOICEVOXを起動する前、起動した直後！１回音声合成したあと、２回したあと、エラーが出る直前などでメモリ使用量を比較した結果を知りたいです。

**Comment by YouCuber** [comment]
[nvidia-smi_log.txt](https://github.com/Hiroshiba/voicevox_engine/files/7046440/nvidia-smi_log.txt)
エンジン起動前～１，２，３…現象発生までのnvidia-smiを添付します。

**Comment by YouCuber** [comment]
>エンジン側がエラーを吐いたらソフトウェア側からエンジンのプロセスを強制的に再起動する、というのを考えていましたが、
>コメントを見て、エンジン側に再読み込みAPIを設けるのも良いなと思いました。

私はymm4経由で使っているので、理想的な応急処置は「http POSTの延長でエンジン異常を検出したらリスタートして再度エンジンに処理依頼し、極力API発行側に500エラーで返さない。（待ち時間が増えたとしても）」ですね。

構造的にそのようにできるのかは不明ですが、ymm4は500エラー帰ってきたらあきらめてしまうため、CPUモードのエンジンで作ったVOICEVOX連携の音声のあるymm4プロジェクトを開くときにスピードを求めてGPUモードにすると、大部分の音声が生成失敗してしまいます。そのため結局VOICEVOXエンジンをCPUモードで使うしかないという状態に陥っています。

仮にエンジンを再起動するAPIを設けても、ymm4に「500エラーを受けた時に再起動APIを呼び出してから音声合成APIをリトライする対処」を入れてもらわないとymm4プロジェクトを開いただけで待っていれば全音声が合成されるとはならないのであまりうれしくないのです。

**Comment by Hiroshiba** [comment]
いただいた.txtからメモリ量だけ抜き出してみました。
```txt
0）起動前
341MiB /  4096MiB

1）起動直後
1043MiB /  4096MiB

3)1回音声合成後（文字列長はすべてtwitterIDなので"〇〇〇〇〇〇 @TRxxyzyzyzyxx"これくらいです）
1326MiB /  4096MiB

4)2回音声合成後（結構長めのID)
2779MiB /  4096MiB

5)3回音声合成後（かなり長いID）"〇〇っち @XXxxjTK9xx0S4g5Q"  くらいですが
3685MiB /  4096MiB

6)4回音声合成後
3738MiB /  4096MiB

7)5回音声合成後
3782MiB /  4096MiB

8)6回音声合成後
3892MiB /  4096MiB

9)7回音声合成後
3932MiB /  4096MiB

10)8回音声合成後
3943MiB /  4096MiB

11)9回目の音声合成に失敗後
3995MiB /  4096MiB

12)以降audio_queryは500エラー
```

たしかに10MBくらいリークしていそうなことがわかりました。ありがとうございます。

**Comment by Hiroshiba** [comment]
ご意見もありがとうございます。とても参考になりました。

APIは処理が分離していたほうが、エンジン側も連携側も都合が良さそうなので、500エラーは返す方針にしようと思います。

問題は、現状の音声ライブラリの実装だとエンジン側に再起動を持たせることができないんですよね・・・
メモリリークが起きる原因とともに、再起動できるような実装を考えたいと思います。
（もしくはGPU処理ができなかったときに、CPU処理するなどの代替案も検討してみます。）

調査ありがとうございました！！

**Comment by Hiroshiba** [comment]
調査は完了で、対策を別issue https://github.com/Hiroshiba/voicevox_engine/issues/48 で実行していきます。
@YouCuber ありがとうございました！
