### ISSUE TITLE
wavのステレオ出力

### ISSUE THREAD

**Issue by y-chan** [Hiroshiba/voicevox_engine#35]
#31 に付随するような仕様の変更なのですが、現状のwavの出力はモノラルオンリーとなっていると思います。
ソフトウェアの仕様上、ステレオ出力が好まれる場合もあると思います。
なので、これもaudio query上で選べれば良いかなと思っています。

こちらは、すでに解決案を持っているので @Hiroshiba さんが大丈夫であればPRしたいと思います。

**Comment by Hiroshiba** [comment]
はい、大丈夫です。プルリクエストお待ちしています。
