### ISSUE TITLE
APIの仕様変更で外部ソフトウェアからの連携ができなくなる問題をどうすべきか

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox_engine#43]
バージョン0.3.1から0.4.1へのアップデートで、音声合成エンジンのAPIが変わりました。
その影響でYMMとの連携が途切れてしまったという報告をいただきました。
https://twitter.com/m_miharu/status/1429667702092689410

こちら側でできる対策はなにか、どういう需要があるかを議論したいです。

**Comment by Hiroshiba** [comment]
少なくともアナウンスと先行配布はしばらく前から出すべきだと感じました。
３〜７日前にAPI変更があったエンジンだけ先行配布、とかが手として考えられそうですが、少し工数が増えそうです。

**Comment by mura08452** [comment]
ベターな案としては既存APIの仕様を残しつつ、新APIの実装を行い、次回以降のバージョンで旧APIの削除を行う、というものでしょうかね？
工数的には手間になるかと思いますが…

**Comment by isnot** [comment]
サードパーティ側から見てAPI仕様変更は重要な関心事項であるはずです。
私は、voicevoxが単独で栄えるよりも、周りのコミュニティやサードパーティが盛り上がることに興味を持っています。
一方で、voicevoxはまだ走り始めたばかりのプロダクト（それ以前の積み重ねがあることは承知しております）ですから、
API変更を伴うような機能追加や改善は、できることならペースを落とさずにやりたいのだろうとも思います。

私の中ではサードパーティとうまくコミュニケーションできることの重要度は高く、そのために相応の「何か」のために腐心して行きたいです。
とはいえ究極的には、APIを利用する側（サードパーティ、エンドユーザー）の責任で追従していただくしかないかと思います。

前置きが長くなりましたが、実際の対策について意見を述べます。

サードパーティ視点でいうと、「いつAPIに非互換や破壊的変更が起こるか」がある程度予見可能である時、それに備えたり、
もしくは気にせずに（不安が少なく）利用できるのではないかと考えます。

[1] voicevox_engineでは、当面マイナーバージョンが偶数の時に限って、API変更を伴うfeatureをリリースに含めることがある（奇数のときは、必ずAPI互換を保証する）
※参考：将来的に、API互換が壊れる場合には、メジャーバージョンが上がるほどのインパクトだと思います

[2] API非互換が発生するリリースの前に、現行バージョンのパッチバージョンに対して、新しいAPIの定義（openapi.json）をバックポートする→各バージョン毎のopenapi.json（0.1.1, 0.2.0, 0.3.1, 0.4.1, latest=0.4.1, next=0.6.0）を取得できる手段（これもAPIか？）を追加する

2番があると何が嬉しいかというと、サードパーティ側では、従来どおりのAPIを利用しつつ、voicevox側の新しいAPI定義を使って、現行バージョンのデータのバリデーションやマイグレーションを予め実装しておくことができるようになると思われます。（あくまで可能性、任意です）

この2点は必須でもないし、別の手段で同等のことを行う方法もありますので、アイデアとしてはもう少し練ったほうがいいかもしれないです。いち案として考慮いただければ幸いです。

**Comment by Hiroshiba** [comment]
ありがとうございます。たしかにしっかりバージョニングして、過去のものもある程度実行可能な状態にするのが最高だと思いました。

バージョニングする場合、今の仕様だとおそらくAPIエンドポイント・処理・データ構造を全てコピーして残しておくことになると思います。
これはなかなか大変なのと、おそらくそもそもバージョニングしても大多数の人はlatestを叩く気がしていて、手間の割に需要とマッチしないのではという気持ちがあります。

いったん試しに、今後なかなか変わらない頑健なテキスト音声合成の流れを用意してみました。
https://github.com/Hiroshiba/voicevox_engine/blob/8f6ce3bbc0a54b830ef96814d40059e68e76fb09/docs/VOICEVOX%E9%9F%B3%E5%A3%B0%E5%90%88%E6%88%90%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E3%81%A8%E3%81%AE%E9%80%A3%E6%90%BA.md
実際にYMMも（たぶん）この流れを使われたっぽくて、一旦これで良いのかなと思いました。
https://twitter.com/manju_summoner/status/1429860893903376401

**Comment by Hiroshiba** [comment]
バージョンが上がっても、/audio_queryで返ってくる値をそのまま/synthesisに POST すれば音声合成できるようにすることを明記し、頑張って守ることにします。
