### ISSUE TITLE
長い英単語の音声合成用のクエリ作成に失敗する

### ISSUE THREAD

**Issue by uberded** [Hiroshiba/voicevox_engine#57]
## 不具合の内容

長い英単語の音声合成に失敗します。

### OK例

* supercalifragilisticexpialidocious
* Uncopyrightables

### NG例

* pneumonoultramicroscopicsilicovolcanoconiosis
* Honorificabilitudinitatibus
* Antidisestablishmentarianism

### 現象・ログ

run.exeのログ

```
[32mINFO[0m:     127.0.0.1:53897 - "[1mPOST /audio_query?text=pneumonoultramicroscopicsilicovolcanoconiosis&speaker=1 HTTP/1.1[0m" [91m500 Internal Server Error[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\Desktop\VOICEV~2.1\VOICEVOX\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "C:\Users\user\Desktop\VOICEV~2.1\VOICEVOX\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\user\Desktop\VOICEV~2.1\VOICEVOX\fastapi\applications.py", line 208, in __call__
  File "C:\Users\user\Desktop\VOICEV~2.1\VOICEVOX\starlette\applications.py", line 112, in __call__
  File "C:\Users\user\Desktop\VOICEV~2.1\VOICEVOX\starlette\middleware\errors.py", line 181, in __call__
ValueError: [<Phoneme phoneme='e'>, <Phoneme phoneme='s'>, <Phoneme phoneme='u'>]
```

### 再現手順

1. run.exeを起動する
2. 以下のコマンドをPowerShellで実行する

```powershell
PS > curl -Method 'POST' 'http://127.0.0.1:50021/audio_query?text=<特定の英単語>&speaker=1'
```

3. run.exeのコンソールを確認する

### 期待動作

jsonが返答される。

## VOICEVOXのバージョン

0.4.1

## OSの種類/ディストリ/バージョン

*   Windows 10 Home 64bit 20H2 (19042.1165)

## その他

関連する可能性のあるIssue: #55

**Comment by y-chan** [comment]
ちょうどそのエラーを探していました...(#44 でCIの整備をしているものです)
以下の部分で起こるエラーのようです。
https://github.com/Hiroshiba/voicevox_engine/blob/5e04069356e825f9d0584ffd2872b251782e7ead/voicevox_engine/full_context_label.py#L99-L104
これは開発者向け情報ですが、#55 内で教えていただいた資料によると、アクセントにあたる`a2`は1-49しか値を持たないという制限があり、英単語などの言葉の(発音の)区切りがOpenJTalk内で判別できないと思われるものは一つの発音の区切り(`BreathGroup`)扱いになります。
その結果、大きな発音の区切りの中でアクセント番号1-49のすべての数字を使い切り、最後の方で49番が連続して`Mora`の生成が出来ず、問題を引き起こしています。
![image](https://user-images.githubusercontent.com/34832037/131714010-20141a8b-df90-4fa7-b933-707eada30b45.png)

**Comment by Hiroshiba** [comment]
報告＆調査ありがとうございます。

仰るとおり、かなりどうしようもない気がしています・・・。
強いて言うなら、openjtalkを使わずに、長いアクセント句をカタカナに変換し、適当な音素を与えればMoraクラスは生成できるかもしれません。
が、そもそもVOICEVOXは息継ぎなしで５０音をちゃんと発声できないので、頑張らなくてもいいと思います。

といっても、やはりとりあえず動いてほしいというのがユーザーののぞみだと思います。
VOICEROIDで試したところ、どうやら長い場合は後半を読むのを諦めるようでした。
こちらでも同じく、50番目を超えたものはMoraを作らないという処理を入れても良いかもと思いました。

**Comment by buckw6eat** [comment]
#55 と合わせてワークアラウンド出してもよいでしょうか。

**Comment by Hiroshiba** [comment]
@buckw6eat おお！　ぜひお願いします！

**Comment by Hiroshiba** [comment]
ワークアラウンドが実装されたのでいったん閉じます。
