### ISSUE TITLE
audio_queryでサーバが動かなくなる条件がある

### ISSUE THREAD

**Issue by nmori** [Hiroshiba/voicevox_engine#6]
■前提条件
　audio_queryの要求時、speaker >1を指定した場合

■現象
　ステータスコード が500 となり、その後、何を要求しても受け付けなくなる

**Comment by Hiroshiba** [comment]
再現できました。エラーになるのは一旦置いておいて、何もできなくなるのは問題だと思います。

これはエンジン内で用いている音声ライブラリ側の問題のようです。
音声ライブラリ側が受け付けられる最大speaker値を超えていないかを、音声ライブラリ内で確認するのが良さそうです。
その部分はOSS化できていないのと、ソフトウェアユーザーはこの問題に遭遇しないため優先度が低めなので、修正できるまで時間がかかりそうです。

**Comment by takana-v** [comment]
#90 が解決されたので、coreのspeakersを参照して範囲外でないかチェックする事が可能になりました。
ただ、他のエンジン実装でも同じ対応が必要になるので、core側でチェックしたほうがいいかもしれません。

**Comment by Hiroshiba** [comment]
たしかに、core側で判定するほうが良いと思いました。自分のタスクに積んでおこうかなと思います。

どちらにしてもエンジン側にも処理が必要なので、エンジン側にも実装しておき、coreにエラー判定が入ったら置き換えても良いかもしれません。

**Comment by Hiroshiba** [comment]
0.6.0辺りでcore側に判定が入ったのでcloseします！
