### ISSUE TITLE
音素とそのテキスト表記が一対一対応していない

### ISSUE THREAD

**Issue by Yosshi999** [Hiroshiba/voicevox_engine#62]
## 不具合の内容
related to https://github.com/Hiroshiba/voicevox/issues/157#issuecomment-912598077

異なる音素が同じテキストに変換されることがある
以下の例はすべてspeaker=1で`/audio_query`にPOSTした結果の一部

<details>
<summary>shi vs si</summary>

シ:
```
{
          "text": "シ",
          "consonant": "sh",
          "vowel": "i"
}
```

スィ:
```
{
          "text": "シ",
          "consonant": "s",
          "vowel": "i"
}
```

</details>

<details>
<summary>zi vs ji</summary>

ズィ:
```
{
          "text": "ジ",
          "consonant": "z",
          "vowel": "i",
}
```

ジ:
```
{
          "text": "ジ",
          "consonant": "j",
          "vowel": "i",
}
```

</details>

### 再現手順

http://localhost:50021/docs#/%E3%82%AF%E3%82%A8%E3%83%AA%E4%BD%9C%E6%88%90
でtextに「スィ」、speakerに「1」を入力

### 期待動作

textを分ける

* si -> スィ
* shi -> シ　のまま
* zi -> ズィ
* ji -> ジ　のまま

## VOICEVOXのバージョン

0.4.1

## OSの種類/ディストリ/バージョン

Windows 10 Home (19042.1165)

**Comment by Yosshi999** [comment]
#60 にも関連しますが、
https://github.com/Hiroshiba/voicevox/issues/157 でカタカナ文字列 <-> [AccentPhrase](https://github.com/Hiroshiba/voicevox/blob/28dad280e129254f1063a73d85b3d67e33a6b8e1/src/openapi/models/AccentPhrase.ts#L28) の変換関数を実装しようとしていて、このあたりの consonant+vowel -> カタカナ文字列変換の不具合が足かせになってしまってます

いっそのことromkan捨ててengine側に1対1対応が保障されたconsonant+vowel <-> カタカナ文字列対応を実装したほうがいいかもしれません（openjtalkに関係するので世界のどこかにある？）

**Comment by Hiroshiba** [comment]
openjtalkの世界のどこかにあるはずなのですが、見たこと無いんですよね・・・
と思って探してみたら、ありました。
https://github.com/xmeta/Open-JTalk/blob/e91de139af9ed63f1955093115133b3005c2c90b/src/jpcommon/jpcommon_rule_utf_8.h#L32

ただこのリストは最新版ではない可能性があるので、ちゃんと本家のopenjtalkを参考にしたほうが良いかもしれません。

**Comment by Hiroshiba** [comment]
マージされたのでcloseします。
