### ISSUE TITLE
音声合成をキャンセル可能にする

### ISSUE THREAD

**Issue by k-kuroguro** [Hiroshiba/voicevox_engine#64]
## 内容

フロント側では効率的な波形生成のため、ユーザの操作待機中に音声合成を始めており、ユーザがキャンセルしてもバックグラウンドで合成が続行されます。
それを避けるため、ユーザの操作に合わせてAPIで音声合成をキャンセルできるようにしたい。

参考: https://github.com/Hiroshiba/voicevox/issues/190

**Comment by Hiroshiba** [comment]
実行中の音声合成を停止する方法は２つありそうです。

１つ目はeach_cpp_forwarder.dllの中身を変えて停止可能にする方法ですが、これは実装がlibtorchに依存しており、libtorchは計算の停止機能が（おそらく）無く、実装に工夫が必要であまり現実的ではありません。。

２つ目は、APIが実行されるたびにプロセスが立ち上がるようFastAPI（かuvicorn）の設定を変更し、キャンセルされたらプロセスごとkillする方法です。（無理矢理ですが・・・。）

他にもアイデアがあればぜひ！

**Comment by isnot** [comment]
私なりに下調べした参考情報を、羅列してみます。実際に使えるかどうか、VOICEVOXとしての適合性に関してはひとまずおいておいて、ただ並べただけです。ご検討の参考として見てください。

以下の手法を使えば、アプリケーションの実装としてプロセス監視をする必要なく、ただ単に自死すればrespawnしてサービス全体としては継続できるはずです。

## FastAPI＋Uvicorn＋Gunicornという構成でマルチプロセスとプロセス監視（自動respawn）できる

[Running with Gunicorn](https://www.uvicorn.org/#running-with-gunicorn)
副次的に、「run.exeが落ちていてフロントエンド側が応答不可になる」問題が軽減できそうです。

## エンドポイントでRequestオブジェクトを受け取って、「Streamの途中でクライアント側からの切断」を検知する

[FastAPI:Using the Request Directly](https://fastapi.tiangolo.com/ja/advanced/using-request-directly/)
[Starlette:Request.is_disconnected](https://github.com/encode/starlette/blob/84e2dc7bfe35aa82a0db958519810309e73de8f5/starlette/requests.py#L259)

この場合クライアント側では、FetchAPI（ex. OpenAPI Generator / typescript-fetch）ですと、
[AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) に対応するかたちで手を加えることになりそうです。

**Comment by Hiroshiba** [comment]
@isnot なるほど、すごく合理的な方法だと思います！
どうでしょう、せっかくなので（とりあえずサーバー側だけでも）実装してみませんか？

**Comment by takana-v** [comment]
https://github.com/Hiroshiba/voicevox/issues/254 の続きです。


>  exit()はおそらくエンジン全体ではなく、マルチプロセスのうちの１つがexitするんだと思います！

恐らくそうなりますね、失礼しました。

上で挙げられていた方法について調査してみました。

### FastAPI＋Uvicorn＋Gunicorn
これはGunicornがwindowsでは動かないようなので難しそうです。
https://docs.gunicorn.org/en/stable/index.html
> Gunicorn ‘Green Unicorn’ is a Python WSGI HTTP Server for UNIX.

---
こちらのページでプロセスマネージャーがいくつか書いてあったので調査しました。
https://www.uvicorn.org/deployment/
使えそうなのは以下の一つです。

#### circus
https://github.com/circus-tent/circus
0.12(2015/6/2)でwindowsの実験的サポート（現在は不明）
そもそも動くのか、exe化できるのかは要確認です。

その他、計算部分を別スレッド（や別プロセス）で動かしてそれを無理やり止める、という方法でも実装可能かもしれません（無理やりですが）。

### Requestオブジェクトの受け取り
`Request.is_disconnected()`で切断されたかは分かりますが、それを監視する方法が見つかりませんでした。
単純にビジーループで監視するのは良くないですし...

**Comment by Hiroshiba** [comment]
移動ありがとうございます。

なるほど、Gunicornはwindows非対応なんですね。残念です。
Issue https://github.com/benoitc/gunicorn/issues/524

circusは・・・よくわからないですね・・・
そういえばunicornは`--workers INTEGER`でワーカー数を指定できるのですが、こちらはどうなんでしょう。

> 別スレッド（や別プロセス）で動かして

こちらも良い方法に感じました！
PythonはGILがある関係でスレッド（疑似スレッド）が不思議な挙動をするので、プロセスのが良いかもです。

> Request.is_disconnected()で切断されたかは分かりますが、それを監視する方法が見つかりませんでした。

ちょっとググってみたのですが、Requestが来る前段で頑張ればできるかも・・・？
https://github.com/tiangolo/fastapi/issues/2496

**Comment by takana-v** [comment]
> そういえばunicornは--workers INTEGERでワーカー数を指定できるのですが、こちらはどうなんでしょう。

https://github.com/encode/uvicorn/blob/c67ffad08c555e1cfb9f8d7f6b88be46688fd730/uvicorn/main.py#L432
`uvicorn.run`で、文字列を渡さないとworkers機能は使えないようです。
（現状は`generate_app`関数の結果を渡している）

> ちょっとググってみたのですが、Requestが来る前段で頑張ればできるかも・・・？

websocketでは使えそうですが、普通のhttpの接続では方法が見つかりませんでした。
websocketを採用すれば実現できそうですが、下位互換性の問題もあるので難しいかもしれませんね。

**Comment by Hiroshiba** [comment]
> 文字列を渡さないとworkers機能は使えないようです。

なるほどーーー　uvicornをコマンドライン経由で起動して`app`という文字列を与えたときに可能な感じかな・・・
exeファイルにするならどうすればいいか見当がつきませんね・・・

> websocketでは使えそうですが

普通のhttp接続で使える方法ではないんですね、失礼しました。

**Comment by Hiroshiba** [comment]
> Request.is_disconnected()で切断されたかは分かりますが、それを監視する方法が見つかりませんでした。

そういえばこちらですが、ちょっとtime.sleepして`Request.is_disconnected()`を確認し、ループしてまた確認し、というのを繰り返すちょっと愚直な手はあるかなと思いました。

**Comment by takana-v** [comment]
実装するなら以下の感じでしょうか。
*  `/synthesis`を処理している関数
    * 音声合成部分を`multiprocessing`で別プロセスで実行
    * `Request`と`multiprocessing.Process`をグローバル変数に格納
* 別スレッド
    * `Request.is_disconnected()`で接続の確認→切れてるならプロセスをkill 
    * `multiprocessing.Process.is_alive()`でプロセスの生死を確認
    * 1秒sleep

https://docs.python.org/ja/3/library/multiprocessing.html
> プロセスオブジェクトが作成したプロセスのみが start(), join(), is_alive(), terminate() と exitcode のメソッドを呼び出すべきです。

ということなので、接続監視は別プロセスではなく別スレッドの方が良いでしょう。

ただ、少し気になる点があります。
* `torch.multiprocessing`を使う必要があるか
https://pytorch.org/docs/stable/notes/multiprocessing.html
* プロセスの開始方式は`fork`しか使えないのか
> 警告: Unix において、'spawn' あるいは 'forkserver' で開始された場合、 "frozen" な実行可能形式 (PyInstaller や cx_Freeze で作成されたバイナリなど) は使用できません。'fork' で開始した場合は動作します。

**Comment by Hiroshiba** [comment]
処理の流れ、良さそうに感じました！！

よくよく考えてみると、process killしてコアを再起動しようとすると、initializeし直す必要がありそうな気がしてきました。
initializeはかなり時間がかかるので、実はprocess killする方法はあまり現実的ではないかもしれません・・・。

**Comment by takana-v** [comment]
とりあえず自分なりに実装してみました。
https://github.com/takana-v/voicevox_engine/commit/756d788b0e730e1247ff450fd4ae0099a35c0678

別スレッドで通信の切断を監視するのはうまくいきませんでした...
asyncio周りで躓いた感じです。
（イベントループに、切断されたか調べるコルーチン投げても結果が永遠に戻ってこない）

`/reserve_synthesis`で予約IDを取得して、`recv_synthesis`で音声データを取得する感じです。
`/cancel_synthesis`でキャンセルします。

この方法でも再度エンジンを作成する必要がありました。
自環境では2秒ほどかかります。
